askcompany/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

#askcompany settings + django.conf.global_settings
from django.conf import settings
from django.views.generic import TemplateView, RedirectView

# class RootView(TemplateView):
#     template_name = 'root.html'

urlpatterns = [
    #path('', TemplateView.as_view(template_name='root.html'), name='root'),
    #path('',RedirectView.as_view(url='/instagram/'), name='root'),
    #url reverse 적용 예시
    path('',RedirectView.as_view(pattern_name='instagram:post_list'),name='root'),
    path('admin/', admin.site.urls),
    path('blog1/', include('blog1.urls')),
    path('k-instagram/', include('instagram.urls')),
    path('accounts/', include('accounts.urls')),
    path('analysis/', include('analysis.urls')),
]

# 이 설정을 하지 않아도 default로 settings에서 설정해준 media 폴더에 파일이 생성된다.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls))
    ]

blog1/urls.py
from . import views
from django.urls import path

app_name ='blog1'

urlpatterns = [
    path('', views.post_list, name='post_list'), #매핑, 함수를 넘긴다. (일급함수 참고)
]

instagram/urls.py
from django.urls import path, re_path, register_converter
from . import views


class YearConverter:
    regex = r"20\d{2}"

    def to_python(self, value):
        return int(value)


register_converter(YearConverter, "year")
app_name = "instagram"  # URL Reverse에서 Name Spaece 역할을 함

urlpatterns = [
    path("new/", views.post_new, name="post_new"),
    path("<int:pk>/edit/", views.post_edit, name="post_edit"),
    path("<int:pk>/delete/", views.post_delete, name="post_delete"),
    path("", views.post_list, name="post_list"),
    path("<int:pk>/", views.post_detail, name="post_detail"),
    # path('archives/<int:year>/', views.archives_year), # path 사용하기
    # re_path(r'archives/(?P<year>20\d{2})/', views.archives_year) # 정규식 사용하기
    # path(r'archives/<year:year>/', views.archives_year) #custom converter 사용하기
    path("archive/", views.post_archive, name="post_archive"),
    path("archive/<year:year>/", views.post_archive_year, name="post_archive_year"),
]

instagram/models.py
from django.conf import settings
from django.core.validators import MinLengthValidator  # 에러 방지하기 위해 기본 지원되는 validator 사용
from django.db import models
from django.http import HttpRequest, HttpResponse
from django.urls import reverse


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    message = models.TextField(
        validators=[MinLengthValidator(10)]
    )  # 최소 10글자 제약 유효성 검사, admin단에서도 바로 확인 가능
    photo = models.ImageField(
        blank=True, upload_to="instagram/post/%Y%m%d"
    )  # upload_to 옵션을 지정해서 파일을 상세 폴더로 분기함
    tag_set = models.ManyToManyField("Tag", blank=True)  # tag가 없을수도 있어서  blank 지정
    is_public = models.BooleanField(default=False, verbose_name="공개여부")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # 객체에 대한 문자열 제공
    def __str__(self):
        return f"{self.message}"

    def get_absolute_url(self):
        return reverse("instagram:post_detail", args=[self.pk])

    def message_length(self):
        return len(self.message)

    class Meta:
        ordering = ["-id"]

    message_length.short_description = "메세지 글자수"


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, limit_choices_to={"is_public": True}
    )
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

instagram/forms.py
import re

from django import forms
from .models import Post

# 모델 Form  설계
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["message", "photo", "tag_set", "is_public"]  # 이 항목에 대해서만 유효성 검사

    def clean_message(self):
        message = self.cleaned_data.get("message")
        if message:
            message = re.sub(r"[a-zA-Z]+", "", message)
        return message

instagram/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpRequest, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import (
    DetailView,
    ListView,
    ArchiveIndexView,
    YearArchiveView,
    CreateView,
    UpdateView,
    DeleteView,
)

from .models import Post
from .forms import PostForm


# def post_new(request):
#     if request.method == "POST":
#         form = PostForm(request.POST, request.FILES)
#         if form.is_valid():
#             post = form.save(commit=False)
#             post.author = request.user  # 현재 로그인 User Instance
#             post.save()
#             messages.success(request, "포스팅을 저장했습니다.")
#             return redirect(post)  # 저장을 하고 이동이 되게 한다.
#     else:
#         form = PostForm()
#
#     return render(
#         request,
#         "instagram/post_form.html",  # 폼을 보여준다.
#         {
#             "form": form,
#             "post": None,
#         },
#     )


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        messages.success(self.request, "포스팅을 저장했습니다.")
        return super().form_valid(form)


post_new = PostCreateView.as_view()


# @login_required
# def post_edit(request, pk):
#     post = get_object_or_404(Post, pk=pk)
#
#     # 작성자 Check Tip
#     if post.author != request.user:
#         messages.error(request, "작성자만 수정할 수 있습니다.")
#         return redirect(post)
#
#     if request.method == "POST":
#         form = PostForm(request.POST, request.FILES, instance=post)
#         if form.is_valid():
#             post = form.save()
#             messages.success(request, "포스팅을 수정했습니다.")
#             return redirect(post)
#     else:
#         form = PostForm(instance=post)
#
#     return render(
#         request,
#         "instagram/post_form.html",
#         {
#             "form": form,
#             "post": post,
#         },
#     )


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm

    def form_valid(self, form):
        messages.success(self.request, "포스팅을 수정했습니다.")
        return super().form_valid(form)


post_edit = PostUpdateView.as_view()


# @login_required
# def post_delete(request, pk):
#     post = get_object_or_404(Post, pk=pk)
#     if request.method == "POST":
#         post.delete()
#         messages.success(request, "포스팅을 삭제했습니다.")
#         return redirect("instagram:post_list")
#     return render(
#         request,
#         "instagram/post_confirm_delete.html",
#         {
#             "post": post,
#         },
#     )


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    # success_url = reverse("instagram:post_list") # 안됨

    # def get_success_url(self):
    #     return reverse("instagram:post_list") #됨

    success_url = reverse_lazy("instagram:post_list")  # 됨


post_delete = PostDeleteView.as_view()


# @login_required
# def post_list(reqeust):
#     qs = Post.objects.all()
#     q = reqeust.GET.get('q','') # q key가 있으면 가져오고, 없으면 ''
#     if q:
#         qs = qs.filter(message__icontains=q) # 필터링 기능 구현이 됨
#         #instagram/templates/instagram/post_list.html
#     return render(reqeust, 'instagram/post_list.html', {
#         'post_list':qs,
#         'q':q,
#         })

# login_required 추천하는 방법
# @method_decorator(login_required, name='dispatch')
# class PostListView(ListView):
#     model = Post
#     paginate_by = 10


class PostListView(LoginRequiredMixin, ListView):
    model = Post
    paginate_by = 100


# class PostListView(ListView):
#     model = Post
#     paginate_by = 100

post_list = PostListView.as_view()

# ListView 활용
# post_list = ListView.as_view(model=Post, paginate_by=10)


# def post_detail(request: HttpRequest, pk: int) -> HttpResponse:
#     # try:
#     #     post = Post.objects.get(pk=pk) # 포스트 하나를 얻는다.
#     # except Post.DoesNotExist: # DoesNotExist 예외 처리
#     #     raise Http404
#
#     post= get_object_or_404(Post, pk=pk) #예외처리 간단하게 하는 방법
#     return render(request, 'instagram/post_detail.html', {
#         'post':post,
#     })


# post_detail = DetailView.as_view(model=Post)

# get_queryset 재정의
class PostDetailView(DetailView):
    model = Post

    def get_queryset(self):
        qs = super().get_queryset()
        if not self.request.user.is_authenticated:
            qs = qs.filter(is_public=True)
        return qs


post_detail = PostDetailView.as_view()

# def archives_year(request, year):
#     return HttpResponse(f"{year}년 archives")

post_archive = ArchiveIndexView.as_view(
    model=Post, date_field="created_at", paginate_by=10
)

post_archive_year = YearArchiveView.as_view(
    model=Post, date_field="created_at", make_object_list=True
)

instagram/templates/instagram/layout.html
{% load django_bootstrap5 static %}

<!doctype html>
<html lang="ko">
<head>
    <meta charset="utf-8"/>
    <title> {% block title %} {% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap-5.2.2-dist/css/bootstrap.css' %}">
    <script src="{% static 'jquery-3.6.1.min.js' %}"></script>
    <script src="{% static 'bootstrap-5.2.2-dist/js/bootstrap.js' %}"></script>
    <style>
        body {
            padding-top: 5rem;
            padding-bottom: 2rem ;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Fixed navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            {% bootstrap_messages %}
                {% block content %}
                {% endblock content%}
                <hr/>
                &copy; 2022 ask company

        </div>
    </div>
</div>


</body>
</html>

instagram/templates/instagram/post_archive.html
<h2>latest</h2>

{{ latest }}

<h2> date_list</h2>

{% for date in date_list %}
    {{ date.year }}
{% endfor %}

instagram/templates/instagram/post_archive_year.html
<h2> Year </h2>
{{ year }}

<h2> previous_year </h2>
{{ previous_year }}

<h2> next_year </h2>
{{ next_year }}

<h2> date_list </h2>
{{ date_list }}

<h2> object_list </h2>
{{ object_list }}

instagram/templates/instagram/post_confirm_delete.html
{% extends "instagram/layout.html" %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}

        <div class="alert alert-danger">
            정말 삭제하시겠습니까?
        </div>

        <a href="{{ post.get_absolute_url }}" class="btn btn-secondary">
            내용보기
        </a>
        <input type="submit" value="삭제하겠습니다." class="btn btn-danger" />

    </form>
{% endblock content %}

instagram/templates/instagram/post_detail.html
{% extends "instagram/layout.html" %}
{%  load bootstrap4 %}

{% block title %}
    Post Detail pk# {{ post.pk }}
{% endblock title %}

{% block content %}
    <h2>Author: {{ post.author }}</h2>

{% if post.photo %}
    <div>
        <img src="{{ post.photo.url }}"/>
    </div>
{% endif %}

    {{ post.message|linebreaks }}

    <hr/>
    <a href="{% url 'instagram:post_list' %}" class="btn btn-primary">
        목록
    </a>

     <a href="{% url 'instagram:post_edit' post.pk %}" class="btn btn-info">
        수정
    </a>

    <a href="{% url 'instagram:post_delete' post.pk %}" class="btn btn-danger">
        삭제
    </a>

{% endblock content %}

instagram/templates/instagram/post_form.html
{% extends "instagram/layout.html" %}
{% load bootstrap4 %}

{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button class="btn btn-primary">
                저장
            </button>
        {% endbuttons %}

    </form>
    <hr/>

    {% if post %}
        <a href="{{ post.get_absolute_url }}" class="btn btn-secondary">
            내용으로
        </a>
    {% endif %}
    <a href="{% url "instagram:post_list" %}" class="btn btn-primary">
        목록
    </a>
{% endblock %}

instagram/templates/instagram/post_list.html
{% extends "instagram/layout.html" %}
{%  load bootstrap4 %}

{% block title %}
    Instagram / Post List
{% endblock title %}

{% block content %}
    <form action="" method="get">
        <input type="text" name="q" value="{{ q }}"/>
        <input type="submit" value="검색"/>
    </form>

    <!-- margin top과 bottom을 주고 버튼에 스타일을 적용하였다. -->
    <a href="{% url 'instagram:post_new' %}" class="btn btn-primary btn-block mt-3 mb-3">
        새 포스팅
    </a>



    <table class="table table-bordered table-hover">
        <tbody>
            {% for post in post_list %}
                <tr>
                <td>
                    {{ post.pk }}
                </td>
                    <td>
                        {% if post.photo %}
                            <img src="{{ post.photo.url}}" style="width: 100px;"/>
                        {% else %}
                            No Photo
                        {% endif%}
                    </td>
                    <td>
                        <a href={{ post.get_absolute_url }}>
{#                        <a href="{% url "instagram:post_detail" post.pk %}">#}
{#                        <a href="/instagram/{{ post.id }}">#}
                            {{ post.message }}
                        </a>

                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{#    {{ is_paginated }}#}
{#    {{ page_obj }}#}
    {% if is_paginated %}
        {% bootstrap_pagination page_obj size="medium" justify_content="center"%}
    {% endif %}
{% endblock content %}